### ISSUE TITLE
What is char-by-char going to be?

### ISSUE THREAD

**Issue by simondebbarma** [jzhang300/char-by-char#2]
We discuss how to take this fun project forward.

**Option A** - Let the community make whatever they want by creating pull requests on Github. 
**Risk** - Too many pull requests. Code that doesn't do anything. Hijacked by pranks.

**Option B** - Create an actual app where coders can be authenticated and create a system where they are allowed to insert a char. We will also create another repo will be created where code from the app will be pushed daily.
**Risk** - Spambots. Automated char insertion scripts.

______________________________________________________________

**Comment by jzhang300** [comment]
Given how slow the pace of this is project is going to be, it's not really possible to do much "free style" code, since everyone would have to submit a PR of a character per day.

In order for us to execute a meaningful application, the practical thing to do is probably that we need to do some kind project planning in the Github Issues here.  We would need to define what are the next set of code that needs to be written, which are defined in GitHub issues.
